language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "nightly"
cache: pip
script:
 - cd example
 - python setup.py test
install:
 - pip install -r requirements.txt
 - python setup.py install
after_success:
  - bash build.sh
