language: python
python:
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "nightly"
 - "pypy3.5"
cache: pip
script:
 - cd example
 - python setup.py test
install:
 - pip install Cython
 - python setup.py install
